- name: Install MariaDB
  block:
  - name: Install MariaDb
    apt:
      name: mariadb-server
      state: present
  - name: "Install ansible python3 mysql dependency"
    apt:
      name: python3-mysqldb
      state: latest