---
- name: Update apt-get repo and cache
  apt: update_cache=yes cache_valid_time=3600

- name: Install packages
  apt:
    name: 
      - python
      - rsync
      - apache2
    state: present

- name: Copying website conf
  become: true
  copy:
    src: ../../../front.conf
    dest: /etc/apache2/sites-available/000-default.conf
    owner: root
    group: root
    mode: 0644